
        const words = [
            "Abraham",
            "Accounting",
            "Actor",
            "Adam",
            "Afraid",
            "Airplane",
            "Alligator",
            "Ambulance",
            "Angel",
            "Angry",
            "Ants",
            "Apologize",
            "Apple",
            "Art",
            "Attack",
            "Aunt",
            "Baby",
            "Back",
            "Backpack",
            "Bag",
            // "Baggage",
            "Bake",
            // "Balance",
            "Ball",
            "Banana",
            "Baptizing",
            "Bark",
            "Basket",
            // "Basketball",
            "Bat",
            "Battery",
            "Bay",
            "Beach",
            "Beak",
            "Beans",
            // "Bear",
            "Beating",
            "Bed",
            "Bee",
            "Bible",
            "Bike",
            "Bird",
            "Birthday",
            "Bite",
            "Blanket",
            "Boat",
            "Bone",
            "Book",
            "Border",
            "Boring",
            "Bottle",
            "Bowl",
            "Box",
            "Boy",
            "Branch",
            "Bread",
            "Brick",
            "Bridge",
            "Broom",
            "Brown",
            "Bucket",
            "Buffalo",
            "Bug",
            "Building",
            "Bull",
            "Butterfly",
            "Button",
            "Buying",
            "Cake",
            "Calculating",
            // "Calendar",
            "Calling",
            // "Cap",
            "Carrot",
            "Cars",
            "Cat",
            "Caterpillar",
            "Cave",
            "Chain",
            // "Chair",
            "Christian",
            "Cheating",
            // "Cheeseburger",
            "Cheetah",
            "Chicken",
            "Children",
            "Chocolate",
            "Choir",
            "Church",
            "City",
            "Clap",
            // "Class",
            "Cleaning",
            "Clock",
            "Closet",
            "Coach",
            "Coast",
            "Coat",
            "Coconut",
            "Coin",
            "Cold",
            "College",
            "Communication",
            "Company",
            "Computer",
            "Cooking",
            "Cookie",
            "Corn",
            "Cotton",
            "Couch",
            "Cough",
            "Country",
            "Cover",
            "Cow",
            "Crab",
            "Criminal",
            // "Crumb",
            "Cube",
            "Cucumber",
            "Cup",
            // "Curl",
            "Cutting",
            "Dad",
            "Dancing",
            "Danger",
            "Dar es salam",
            "Dark",
            "Date",
            "Dawn",
            "Decimal",
            "Density",
            "Desert",
            // "Desk",
            "Dictionary",
            "Digging",
            "Dinosaur",
            "Ditch",
            "Doctor",
            "Dog",
            "Door",
            // "Drain",
            "Drawer",
            "Drawing",
            "Dream",
            "Drill",
            "Drinking",
            // "Dripping",
            "Driving",
            "Drought",
            "Drum",
            "Duck",
            "Duster",
            "Eagle",
            "Ear",
            "Earth worm",
            "Earth",
            "Earthquake",
            // "Eating ",
            "Economics",
            "Egg",
            "Egypt",
            "Elbow",
            "Electricity",
            "Elephant",
            "End",
            "Equator",
            "Excellent",
            "Excersize book",
            "Excersize",
            "Eye",
            "Face",
            // "Fade",
            "Falling",
            "Far",
            "Farm",
            "Fast",
            "Fasting",
            "Father",
            "Feather",
            "Feet",
            "Fiancé",
            "Fighting",
            "Finger",
            "Fire",
            "Firefighter",
            "First",
            "Fish",
            "Fishing",
            "Flag Pole",
            "Flag",
            "Flamingo",
            "Flood",
            "Flower",
            "Fly",
            "Food",
            "Football",
            "Fork",
            "Frame",
            "Freedom",
            "French",
            "Frog",
            "Fruit",
            "Fur",
            "Future",
            // "Gap",
            "Garbage",
            "Garden",
            "Gasoline",
            "Generator",
            "Ghost",
            // "Ginger",
            "Giraffe",
            "Glasses",
            "Globalization",
            "Glue",
            "Goat",
            "Going",
            "Gold",
            "Good",
            "Grapes",
            "Grass",
            "Great-Grandmother",
            "Green",
            "Guitar",
            // "Hail",
            // "Hair",
            "Happy",
            "Hard",
            "Hat",
            "Head",
            "Heart",
            "Heaven",
            "Helicopter",
            "Hiding",
            "Hill",
            "Hippopotamus",
            "Hoe",
            "Homeless",
            "Homework",
            "Honey",
            // "Honk",
            "Hoof",
            "Horse",
            "Hospital",
            "Hot",
            "House",
            "Ink",
            "Insulting",
            "Irrigation",
            "Island ",
            "Ivory",
            "Jacket",
            "Jail",
            // "Jar",
            "Jaw",
            "Jeans",
            "Jumping",
            "Jonah",
            "Key",
            "King David",
            "Kitten",
            "Knee",
            "Ladybug",
            "Lamp",
            "Laptop",
            "Laughing",
            "Laundry",
            "Leaf",
            "Legs",
            "Letter",
            "Lie",
            "Light Bulb",
            "Light",
            "Lightning",
            "Line",
            "Lion",
            "Lip",
            "List",
            "Litre",
            "Living Room",
            "Lizard",
            "Lock",
            "Love",
            "Lunar eclipe",
            "Lunch",
            "Lung",
            "Machine",
            // "Mail",
            "Magnet",
            "Malaria",
            "Man",
            "Mango",
            "Mark",
            // "Markboard",
            "Middle",
            "Midnight",
            "Mold",
            "Monkey",
            "Moon",
            "Morning",
            "Moses",
            "Mosquito net",
            "Motorcycle",
            "Mountain",
            "Mouse",
            "Mouth",
            "Movie",
            "Mushroom",
            "Music",
            "Muslim",
            "Nail",
            "National Park",
            "Neck",
            "Neighbor",
            "Netball",
            "Nice",
            "Nigeria",
            "Night",
            "Noah",
            "Nose",
            "Nurse",
            "Oar",
            "Ocean",
            "five hundred and seventy-two",
            "Orange",
            "Organ",
            "Orphan",
            "Ostrich",
            "Oval",
            "Owner",
            "Page",
            "Pain",
            "Pan",
            // "Pancake",
            "Panda",
            "Panic",
            "Pants",
            // "Paper",
            "Parent",
            "Park",
            "Patriot",
            "Pastor",
            // "Peace",
            "Peanut",
            // "Pen",
            "Pencil",
            "Pepper",
            "Person",
            "Peter",
            // "Phone",
            "Photo",
            // "Pie",
            "Pilot",
            "Pink",
            // "Pirate",
            "Plant",
            "Plastic",
            "Playground",
            "Point",
            "Police",
            "Pond",
            "Potato",
            "Power outage",
            "Praying",
            "Preaching",
            "Prime minister",
            "Proverb",
            "Print",
            "Psalms",
            "Puddle",
            "Pushing",
            "Puzzle",
            "Rabbit",
            "Rain season",
            "Rain",
            "Rainbow ",
            "Rat",
            "Receipt",
            "Refrigerator",
            "Religion",
            "Reservoir",
            "Rib",
            "Rice",
            "Ring",
            "River",
            "Rock",
            // "Rocket",
            "Roof",
            "Root",
            "Rubber",
            "Ruler",
            "Sack",
            "Sad",
            // "Sailboat",
            "Sale",
            "Sand",
            "Scar",
            "School",
            "Scorpion",
            "Sea",
            "Searching",
            "Seashell",
            "Second",
            // "Shark",
            "Shaving",
            "Sheep",
            "Shelf",
            "Ship",
            "Shipwreck",
            "Shirt",
            "Shoe",
            "Shovel",
            "Sick",
            "Sin",
            "Sir Victor",
            "Sleeping",
            "Smart",
            "Smile",
            "Snail",
            "Snake",
            "Snarling",
            "Sock",
            "Soda",
            "Solution",
            "Speakers",
            "Spider Web",
            "Spider",
            "Spoon",
            "Sponge",
            "Square",
            "Star",
            "Starfish",
            "Start",
            "Stay",
            "Steam",
            "Step",
            "Stick",
            "Sticking",
            "Stop",
            "Store",
            "Storm",
            "Stove",
            "String",
            "Stubborn",
            "Studying",
            "Stutter",
            "Suit",
            "Sun",
            "Sunflower",
            "Sunglasses",
            "Sunset",
            "Sweater",
            "Sweeping",
            "T-Shirt",
            "TV",
            "Table",
            "Tail",
            "Taxi",
            "Tea",
            "Teacher",
            "Team",
            "Tent",
            "Throwing",
            "Thunderstorm",
            // "Tide",
            "Tie",
            "Time",
            "Tire",
            "Tissue",
            // "Toast",
            "Toe",
            "Toothpaste",
            "Torch",
            "Tounge Twister",
            "Toy",
            "Train",
            "Transportation",
            "Trap",
            "Tree",
            "Triangle",
            "Trip",
            "Truck",
            // "Turkey",
            "Turtle",
            "Tusk",
            // "Twist",
            "Uganda",
            "Umbrella",
            "Understanding",
            "Unit",
            "Vacation",
            "Valley",
            "Vein",
            "Violent",
            "Volcanic eruption",
            // "Volleyball",
            "Wall",
            "Wallet",
            "warm",
            "Washing",
            "Watch",
            "Water",
            "Wearing",
            "Wedding",
            // "Whale",
            "Whistle",
            "Win",
            "Wind",
            // "Window",
            "Wing",
            "Woman",
            "Womb",
            "Wood",
            "Words",
            "Work",
            "Worm",
            "Yellow",
            "Zebra",
            "Zigzag",
        
        ];
        let completedWordsList=document.getElementById("pastWordsList");

        function showRandomWord() {
            const randomIndex = Math.floor(Math.random() * words.length);
            addWordToList(document.getElementById("word").textContent);
            document.getElementById("word").textContent = words[randomIndex];
            startTimer();
        }

        function addWordToList(word) {
            let newItem=document.createElement("li");
            newItem.textContent=word;
            completedWordsList.appendChild(newItem);
        }
        function clearWordList(){
            completedWordsList.innerHTML="";
        }


